name: "anisf.dkr-terraform.ubuntu"

on:
  push:
    paths:
      - 'ubuntu/**'
      - '.github/workflows/ubuntu.yml'
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version:
        - devel
        - latest
        terraform_version:
        - 1.0.11
        - 0.15.5
        - 0.14.11
        - 0.13.7
        - 0.12.31
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build terraform image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ubuntu
          file: ./ubuntu/Dockerfile
          tags: anisfathallah/terraform:${{ matrix.terraform_version }}-ubuntu-${{ matrix.ubuntu_version }}
          build-args: |
            TERRAFORM_VERSION=${{ matrix.terraform_version }}
            UBUNTU_VERSION=${{ matrix.ubuntu_version }}

      - name: Test builded image
        uses: addnab/docker-run-action@v1
        with:
          image: anisfathallah/terraform:${{ matrix.terraform_version }}-ubuntu-${{ matrix.ubuntu_version }}
          options: -v ${{github.workspace}}:/workspace
          run: |
            id
            cd /workspace
            terraform version

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'anisfathallah/terraform:${{ matrix.terraform_version }}-ubuntu-${{ matrix.ubuntu_version }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
